-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Profiles Table
create table public.profiles (
  id uuid references auth.users not null primary key,
  username text,
  avatar_url text,
  total_pt integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Learning Stats Table
create table public.learning_stats (
  user_id uuid references public.profiles(id) not null primary key,
  total_study_time integer default 0,
  total_correct integer default 0,
  total_wrong integer default 0,
  streak_days integer default 0,
  last_study_date date,
  updated_at timestamptz default now()
);

-- Step Progress Table
create table public.step_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  step_id text not null,
  is_completed boolean default false,
  attempts integer default 0,
  errors integer default 0,
  best_time integer,
  last_attempt_at timestamptz default now(),
  unique (user_id, step_id)
);

-- User Achievements Table
create table public.user_achievements (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  achievement_id text not null,
  unlocked_at timestamptz default now(),
  unique (user_id, achievement_id)
);

-- Point History Table
create table public.point_history (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  amount integer not null,
  reason text not null,
  created_at timestamptz default now()
);

-- User Submissions Table
create table public.user_submissions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  challenge_id text not null,
  code text not null,
  status text not null,
  error_message text,
  execution_time integer,
  submitted_at timestamptz default now()
);

-- RLS Policies
alter table public.profiles enable row level security;
alter table public.learning_stats enable row level security;
alter table public.step_progress enable row level security;
alter table public.user_achievements enable row level security;
alter table public.point_history enable row level security;
alter table public.user_submissions enable row level security;

-- Profiles Policies
create policy "Users can view own profile" on public.profiles
  for select using (auth.uid() = id);
create policy "Users can update own profile" on public.profiles
  for update using (auth.uid() = id);

-- Learning Stats Policies
create policy "Users can view own stats" on public.learning_stats
  for select using (auth.uid() = user_id);
create policy "Users can insert own stats" on public.learning_stats
  for insert with check (auth.uid() = user_id);
create policy "Users can update own stats" on public.learning_stats
  for update using (auth.uid() = user_id);

-- Step Progress Policies
create policy "Users can view own step progress" on public.step_progress
  for select using (auth.uid() = user_id);
create policy "Users can insert own step progress" on public.step_progress
  for insert with check (auth.uid() = user_id);
create policy "Users can update own step progress" on public.step_progress
  for update using (auth.uid() = user_id);

-- User Achievements Policies
create policy "Users can view own achievements" on public.user_achievements
  for select using (auth.uid() = user_id);
create policy "Users can insert own achievements" on public.user_achievements
  for insert with check (auth.uid() = user_id);

-- Point History Policies
create policy "Users can view own point history" on public.point_history
  for select using (auth.uid() = user_id);
create policy "Users can insert own point history" on public.point_history
  for insert with check (auth.uid() = user_id);

-- User Submissions Policies
create policy "Users can view own submissions" on public.user_submissions
  for select using (auth.uid() = user_id);
create policy "Users can insert own submissions" on public.user_submissions
  for insert with check (auth.uid() = user_id);

-- Function to handle new user
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (new.id, new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'avatar_url');
  
  insert into public.learning_stats (user_id)
  values (new.id);
  
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to create profile on signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- RPC for incrementing points atomically
create or replace function public.increment_pt(amount int)
returns void as $$
begin
  update public.profiles
  set total_pt = total_pt + amount,
      updated_at = now()
  where id = auth.uid();
end;
$$ language plpgsql security definer;

